[build]
command = "hugo --gc --minify"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV           = "production"
<<<<<<< HEAD
HUGO_VERSION       = "v0.125.4"
NODE_VERSION       = "v20.11.0"
NPM_VERSION        = "10.2.4"
=======
HUGO_VERSION       = "0.120.1"
NODE_VERSION       = "v18.12.1"
NPM_VERSION        = "8.19.2"
>>>>>>> origin/main

[context.split1]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --enableGitInfo"

    [context.split1.environment]
    HUGO_ENV     = "production"
<<<<<<< HEAD
    HUGO_VERSION = "v0.125.4"
    NODE_VERSION = "v20.11.0"
    NPM_VERSION  = "10.2.4"
=======
    HUGO_VERSION = "0.120.1"
    NODE_VERSION = "v18.12.1"
    NPM_VERSION  = "8.19.2"
>>>>>>> origin/main

[context.deploy-preview]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

    [context.deploy-preview.environment]
<<<<<<< HEAD
    HUGO_VERSION = "v0.125.4"
    NODE_VERSION = "v20.11.0"
    NPM_VERSION  = "10.2.4"
=======
    HUGO_VERSION = "0.120.1"
    NODE_VERSION = "v18.12.1"
    NPM_VERSION  = "8.19.2"
>>>>>>> origin/main

[context.branch-deploy]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"

    [context.branch-deploy.environment]
<<<<<<< HEAD
    HUGO_VERSION = "v0.125.4"
    NODE_VERSION = "v20.11.0"
    NPM_VERSION  = "10.2.4"
=======
    HUGO_VERSION = "0.120.1"
    NODE_VERSION = "v18.12.1"
    NPM_VERSION  = "8.19.2"
>>>>>>> origin/main

[context.next.environment]
HUGO_ENABLEGITINFO = "true"